### ISSUE TITLE
CorStructs for Residuals

### ISSUE THREAD

**Issue by KOBForest** [dmbates/MixedModels.jl#176] opened 2019-05-24 11:37 UTC
Using the nlme R package, it is possible to specify a covariance matrix form (i.e. CS, Symm) for the residuals.
Using the systolic blood pressure data set in the MethComp package, and filtering out one of the three methods (J,S,R), such that two remain. we could fit the following model

mm1 = lme(y - meth,
   data = sbp,
   random = list(item=pdSymm( ~ meth-1)),
   weights=varIdent(form= ~1|meth),
   correlation = corSymm(form= ~1 | item/repl),
   method="ML")

Is it possible to do something similar for the residuals with MixedModels.jl?

**Comment by KOBForest** [comment] 2019-05-24 11:39
Hi Professor Bates.
I meant to add in a greeting and an expression of thanks for your time.
Kevin

**Comment by PharmCat** [comment] 2019-07-10 09:55
I think it also lack of lme4 package for R. And implemented in lme like this:

```
model5.3.fit <- lme(activate ~ region.f*treat,
random = ~ treat | animal,
weights = varIdent(form = ~ 1 | treat),
data = rat.brain)
```
expression: weights = varIdent(form = ~ 1 | treat)

Example from: Brady T. West. Linear Mixed Models: A Practical Guide Using Statistical Software p 220

And of course I would really like to see this functionality in MixedModel.jl

**Comment by dmbates** [comment] 2019-08-08 16:33
My emphasis in this package has been on fitting mixed-effects models and allowing for complex structures in the random effects.  In the `nlme` package we were aiming for a general system for modeling variance structures and, to my mind, it just got too confusing.  The disadvantage of having three or four different ways of modifying the structure of the model is that you sometimes get cross-talk and the optimization problem can be overdetermined without that being obvious.

The thing we didn't do in the `nlme` package was allow for multiple, crossed random effects terms.  That was the change in `lme4` and now in this package.  Also, we understand the structure of the mixed-effects better now and can solve those problems more effectively.

I think it is possible to wrap optimization of parameters in, e.g., a weights structure, around the mixed-effects model structure.  If someone wanted to try to do this, either in a package that depends on `MixedModels` or in `MixedModels` itself, I could advise them.  It is unlikely I will do it myself.  Be aware though that the tricky part is often trying to work out the user interface.  The "back end" of actually doing the optimization is usually more straightforward.

**Comment by KOBForest** [comment] 2019-08-10 14:14
Thanks for that. For other readers, I will provide a bit clarity as to what I am doing. 

I am attempting to use LME models to compute the variance of differences $s^2_{D}$ in measurements
between various devices, where multiple measurements are taken successively on each item by each method.

This is the method comparison problem (i.e. Bland Altman plot), but with replicate measurements.

An estimate for $s^2_{D}$  can be computed using the between-item and within-item variances (i.e. using random effects and 
residual covariance matrices).

(Here is an implementation using nlme: https://www.londonr.org/using-lme-models-for-method-comparison-studies/ )

Ideally it is best to get estimates for each method for both random effects *AND* the error term.

One might be tempted to use the variance of the residuals as an estimate for $\sigma^2{\epsilon m }$. But this approach would just serve to court public outrage.

**Comment by PharmCat** [comment] 2019-08-12 09:55
Dear dmbates, contributors and all, could you kindly tell me where can I find literature source for computation techniques for MixedModels. I found "Improved Iterative Schemes for REML Estimation of Variance Parameters in Linear Mixed Models", Emma Jane Knight, but there i didn't found concrete and clear solution. May be, you can recommend source with (step-by-step) implementation and explanation (for dummies).

**Comment by dmbates** [comment] 2019-08-12 18:26
You could start at a recent paper, https://nextjournal.com/dmbates/complexity-in-fitting-linear-mixed-models/  That paper includes a link to our 2015 J. Statist. Software paper describing in more detail the derivation and computational methods for the [`lme4` package](https://github.com/lme4/lme4) for R.

**Comment by PharmCat** [comment] 2019-08-13 15:43
> 
> 
> You could start at a recent paper, https://nextjournal.com/dmbates/complexity-in-fitting-linear-mixed-models/ That paper includes a link to our 2015 J. Statist. Software paper describing in more detail the derivation and computational methods for the [`lme4` package](https://github.com/lme4/lme4) for R.

It is unreal even to try make enything wihout deep understanding of mixed model, I try to understand mixed model described as: y = Xβ + Zγ + ε

So, I have read different sources and made own understanding of problem, if I mistaken, I hope you can kindly suggest me way to getsome solution. Lets try to denote:
 
n - number of observation;
p - number of fixed effects constants;
q - number of random effects;

y - n×1 vector of dependent variable;
β - p×1 vector of fixed effects parameters;
γ - q×1 vector of random effects parameters;
ε - n×1 vector of residual error;

X - n×p design matrix of fixed effects;
Z - n×q design matrix of random effects;

G - The covariance matrix of random effects;
R - The n×n covariance matrix of ε;

V - The n×n covariance matrix of y;

ε is distributed as N(0, R)
γ is distributed as N(0, G)
y is distributed as N(Xβ, V), where V = ZGZ' + R

So we should make some asomption about G and R matrix (in simple case G = σI, where σ - within individual residual(random) and R = σI, where σ - residual deviations of different individual);

I suppose, we can make asomption about G from structure of random effects, and define G as block diagonal matrix with elemens I*[σ1, σ2, ...], where σ1, σ2 - residuals for different grouping factors (for example, random effect - patient and grouping factor suquence with 2 levels "TR" and "RT" will leads to element I*[σtr, σrt], where σtr, σrt - unknown variance paramethers);

I suppose, R matrix also we can represent as diagonal block matrix, but structure of each element less clear. For example, lest suppose that we can construct this matrix with unknown parameters σe1, σe2 and known structure.

For finding unknown parameters (σtr, σrt, σe1, σe2) we can use likelihood methods ML or REML,

for ML we shold maximize log-likelihood function  lML = -N/2*log(2π) - 1/2*log(|V|) - 1/2*(y-Xβ)'*inv(V)*(y-Xβ), where: 
|V| - determinant of V
inv(V) - inverted V

for lREML = -(N-p)/2*log(2π) - 1/2*log(|X'X|) - 1/2*log(|V|) - 1/2*log(|X'*inv(V)*X|) - 1/2*(y-Xβ)'*inv(V)*(y-Xβ), where:
|X'X| - determinant X'X
|V| - determinant of V
|X'*inv(V)*X| - determinant of X'*inv(V)*X

β = inv(X'*inv(V)*X)*X'*inv(V)*y

If I'am not mistaken we cat maximize ML/REML with unknown parameters (σtr, σrt, σe1, σe2)  with Newton algorithm:

σi = σi-1 - inv(H)*g, where:

σi - variance parameters values on i step
σi-1 - variance parameters values on i-1 step
inv(H) - Inverted Hessian matrix of log-likelihood function
g - gradient vector of log-likelihood function

I suppose, H and g we can get with AD packages. 

Some questions is not absolute clear:
At first how to construct G and R matrices and how to chose starting values for them for the log-likelihood function starting point. 
How to chose β for log-likelihood function.
Can we use estimation of β = inv(X'*X)*X'*y?

log-likelihood function includes β vector, is it important for maximization?
For example, what we should do:

   1. Get β = inv(X'*X)*X'*y (or somehow another)
   2. Maximize log-likelihood function with constant β 
   3. Get β = inv(X'*inv(V)*X)*X'*inv(V)*y
   
and stop, or we shold iterate 2 and 3 steps until convergence?

**Comment by dmbates** [comment] 2019-08-13 16:31
You can write the model as you wish but that is not the way that methods in this package work. The methods in this package use the solution to a penalized least squares problem to provide the profiled log-likelihood as a function of a constrained parameter vector that defines the relative covariance factor.  You are welcome to write `inv(V)`, etc. but that is just a set of equations.  When you have a million observations it isn't a good idea to try to evaluate the inverse of a matrix of size 1 million by 1 million for each iteration.  That is why the penalized least squares method is vastly superior to the generalized least squares.

**Comment by palday** [comment] 2019-09-29 15:04
Duplicate of #51

**Closed by palday** 2019-09-29 15:04 UTC
