### ISSUE TITLE
Fitting models with known covariance matrices

### ISSUE THREAD

**Issue by urchgene** [dmbates/MixedModels.jl#158] opened 2019-01-17 17:11 UTC
Dear Prof. Bates,

Greetings..

Over many decades, you have provided materials, softwares, videos and many teaching aids for many people to understand mixed models. Thank you so much for this!

With Julia comes a lot of efficiency and large data modeling. In many applications in agriculture and human genetics, genomic information is used to make a covariance matrix to fit these mixed models. 

Is there a work around here or could you show an example how this can be done here?

An open dataset used a lot is the WheatData in the R BGLR package.
The cov mat is mostly computed simply as 
```M*M'/c``` where ```M``` is a matrix of genomic info for many subjects (rows) and ```c``` is a constant which can be ```mean(diag(M*M'))```. 

Will be nice to see an example or something from you regarding this.

Thanks.

Uche.

**Comment by PharmCat** [comment] 2019-01-17 22:12
Strongly waiting definition/implementation of application covariance structures like: Heterogeneous Compound Symmetry, Factor Analytic, Autoregressive and some more. No life without!

**Comment by palday** [comment] 2019-09-29 15:26
Potential duplicate of #51.

**Comment by palday** [comment] 2019-09-29 16:33
@PharmCat You can still get compound symmetry by clever specification of the random effects.

For example [adapted from here](https://pages.stat.wisc.edu/~bates/UseR2008/WorkshopD.pdf), you fit an unconstrained model like so:
```julia

julia> using DataFrames, MixedModels, RData, RCall

julia> machines = rcopy(R"nlme::Machines");

julia> contrasts = Dict(:Machine=>DummyCoding());

julia> m = fit!(LinearMixedModel(@formula(score ~ Machine + (1 + Machine | Worker)),machines, contrasts=contrasts))
Linear mixed model fit by maximum likelihood
 score ~ 1 + Machine + (1 + Machine | Worker)
   logLik    -2 logLik      AIC         BIC     
 -108.208914  216.417828  236.417828  256.307668

Variance components:
              Column     Variance   Std.Dev.   Corr.
 Worker   (Intercept)  13.81760447 3.7172039
          Machine: B   28.68496515 5.3558347  0.49
          Machine: C   11.24097825 3.3527568 -0.36  0.30
 Residual               0.92463436 0.9615791
 Number of obs: 54; levels of grouping factors: 6

  Fixed-effects parameters:
───────────────────────────────────────────────────
             Estimate  Std.Error   z value  P(>|z|)
───────────────────────────────────────────────────
(Intercept)  52.3556     1.53437  34.1218    <1e-99
Machine: B    7.96667    2.20988   3.60502   0.0003
Machine: C   13.9167     1.40579   9.89956   <1e-22
───────────────────────────────────────────────────
```

And the associated compound symmetric model like so:

```julia
julia> machines.worker_machine = string.(machines.Worker,":",machines.Machine);

julia> contrasts = Dict(:Machine=>DummyCoding(), :worker_machine=>DummyCoding());

julia> m_cs = fit!(LinearMixedModel(@formula(score ~ Machine + (1 | Worker) + (1|worker_machine)),machines, contrasts=contrasts))
Linear mixed model fit by maximum likelihood
 score ~ 1 + Machine + (1 | Worker) + (1 | worker_machine)
   logLik   -2 logLik     AIC        BIC    
 -112.63472  225.26945  237.26945  249.20335

Variance components:
                    Column    Variance   Std.Dev.  
 worker_machine (Intercept)  11.5398334 3.39703304
 Worker         (Intercept)  19.0487123 4.36448305
 Residual                     0.9246299 0.96157679
 Number of obs: 54; levels of grouping factors: 18, 6

  Fixed-effects parameters:
───────────────────────────────────────────────────
             Estimate  Std.Error   z value  P(>|z|)
───────────────────────────────────────────────────
(Intercept)  52.3556     2.26924  23.0718    <1e-99
Machine: B    7.96667    1.9873    4.0088    <1e-4 
Machine: C   13.9167     1.9873    7.00281   <1e-11
───────────────────────────────────────────────────
```

As specified in all the other related issues (e.g. #51, #176), implementing structured covariance matrices isn't on the todo list, but pull requests are welcome. For one possible strategy, look at the implemention of `zerocorr!` ([action on model](https://github.com/dmbates/MixedModels.jl/blob/e409685aa7ad99428cafba41d63c6f9bcd144fd9/src/linearmixedmodel.jl#L678-L705) and [action on RE matrices](https://github.com/dmbates/MixedModels.jl/blob/e409685aa7ad99428cafba41d63c6f9bcd144fd9/src/remat.jl#L426-L434)), which modifies the random effects matrices of a constructed model to force zero correlation between the different random slopes. Similar strategies may work for other covariance structures.

For models where the (co)variance is known (and not just its structure), you're heading towards the types of models used in meta-analysis. The `metafor` project in R has [some documentation](http://www.metafor-project.org/doku.php/tips:rma_vs_lm_lme_lmer) on this and how they relate to the types of models that lme4 and MixedModels.jl can fit. Again, with the right modifications to the model's internal structure before fitting as in `zerocorr!`, you could fit these types of models, but this isn't on the todo list. Pull requests are welcome.

**Closed by palday** 2019-09-29 16:33 UTC

**Comment by skyee1** [comment] 2021-09-29 15:12
how to definition/implementation of application covariance structures like: Factor Analytic
For example(SAS code)
`
proc mixed data=highcv;
class subject seq per trt;
model lcmax=seq per trt/ddfm=satterth;
random trt/sub=subject type=fa0(2);
repeated /group=trt sub=subject;
estimate “组别” trt -1 1/cl alpha=0.1;
ods output Estimates=est;
run;
`

**Comment by PharmCat** [comment] 2021-09-29 22:09
> how to definition/implementation of application covariance structures like: Factor Analytic For example(SAS code) `proc mixed data=highcv; class subject seq per trt; model lcmax=seq per trt/ddfm=satterth; random trt/sub=subject type=fa0(2); repeated /group=trt sub=subject; estimate “组别” trt -1 1/cl alpha=0.1; ods output Estimates=est; run;`

Structured repeate effect implemented in [Metida.jl](https://github.com/PharmCat/Metida.jl) (Heterogeneous Compound Symmetry can be used instead Factor Analytic for BE studies)

**Comment by palday** [comment] 2021-09-29 22:43
@skyee1 As indicated earlier in this issue, we (the MixedModels.jl developers)  have no plans to implement restricted covariance structures for the random effects. I also don't speak SAS (and do not have access to an SAS license) and so don't really understand what you're requesting. We do have `MixedModels.rePCA` and `MixedModels.PCA`, which may get you a step further due to the deep relationship between PCA and factor analysis. 

We're happy to look at pull requests adding restricted covariance structures via the same mechanism as `zerocorr`. 

I'm locking this issue now.
